[build]
  command = "npm run build"
  publish = "frontend/dist"
  functions = "backend/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "20"
